_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 12
                - 45
                - 55
            "2":
                - 1
                - 12
                - 45
                - 55
            "3":
                - 13
                - 23
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
